#价格
price: 50000.0
#钱不足的消息
more-money: '§b[天気の子]§a你不是100％晴女！ (至少需要%.1f元)'
#晴天的消息
no-storm: '§b[天気の子]§a当前天气是晴天！'
#玩家的消息
player-msg: '§b[天気の子]§a你献祭了自己的肉身，成功息怒了雨神的怒火！'
#广播的消息
broadcast-msg: '§b[天気の子]§a[晴女]§d%s§a献祭了自己的肉身，成功息怒了雨神的怒火！'
